### PR TITLE
Feat add filter dir option with more common default

### PR DESCRIPTION
**Pull request by JaosnHsieh**
add Filter directories `['node_modules','.git', 'build', 'dist']` by default and option to override it.

### CODE REVIEW

**Comment by JacksonTian** [comment]
Thank you for contribution.

**Comment by JacksonTian** [comment]
The test cases failed. Could you fix it?

**Comment by JaosnHsieh** [comment]
Fixed.

**Comment by JacksonTian** [comment]
released in v1.1.0.

**Pull request merged**
